# Generated by Django 4.1.1 on 2022-09-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Rooms',
        ),
    ]
